---
driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: chef_solo
  require_chef_omnibus: 12
  data_path: test/shared

platforms:
  - name: centos-7.1
  - name: ubuntu-14.04
  - name: debian-8.0
  - name: fedora-21
  - name: amazon-2017
    driver:
      name: ec2
      instance_type: t2.large
      region: us-east-2
      security_group_filter:
        tag: Name
        value: test-kitchen
      associate_public_ip: true
      tags:
        Name: chef-java_se-amazon
        owner: <%= ENV['USER'] %>
    transport:
      username: ec2-user
  - name: amazon2
    driver:
      image_search:
        owner-id: 137112412989
        name: amzn2-ami-hvm-*
      name: ec2
      instance_type: t2.large
      region: us-east-2
      security_group_filter:
        tag: Name
        value: test-kitchen
      associate_public_ip: true
      tags:
        Name: chef-java_se-amazon
        owner: <%= ENV['USER'] %>
    transport:
      username: ec2-user
  - name: windows-2012r2
    driver:
      box: dhoer/windows-2012r2

suites:
  - name: default
    run_list:
      - recipe[java_se::default]
    excludes:
      - windows-2012r2
  - name: alt_home
    run_list:
      - recipe[java_se::default]
    includes:
      - windows-2012r2
    attributes:
      java_se:
        java_home:
          C:\my\java\jdk
        win_jre_home:
          C:\my\java\jre
